### ISSUE TITLE
Viewing any public event while not root throws NRException

### ISSUE THREAD

**Issue by EidolonForgery** [DistantEye/HappeningsDotNetC#1]
Steps to reproduce:
Make an event as the administrator account
Do not add the other user to the event, but leave it public
In a container tab, log in as the other user and try to view root's calendar and click on the event.

Results:

`System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=HappeningsDotNetC
  StackTrace:
   at HappeningsDotNetC.Controllers.HappeningController.View(Guid id) in C:\Users\Black\source\repos\HappeningsDotNetC\HappeningsDotNetC\Controllers\HappeningController.cs:line 40
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
`

**Comment by DistantEye** [comment]
Should be fixed in latest. Missing null check in one of the optional conditionals

**Comment by EidolonForgery** [comment]
Fixed in commit [b5dec8c](https://github.com/DistantEye/HappeningsDotNetC/commit/b5dec8c99321fed7c8a16312a33e13cca7c0aaa0)
